# Generated by Django 6.0.4 on 2026-04-22 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_alter_etablissement_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etablissement',
            name='frais_application_actives',
            field=models.BooleanField(default=True, help_text="Permet d'activer ou de désactiver les frais d'application (TCA)", verbose_name="Activer les frais d'application"),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='montant_frais_application',
            field=models.IntegerField(default=70, help_text="Montant en FCFA des frais d'application par article", verbose_name="Montant des frais d'application par article"),
        ),
    ]
