# Generated by Django 6.0.4 on 2026-04-21 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_commande_lignecommande'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='reference',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='session',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='session',
            field=models.CharField(default='S124356', max_length=20),
            preserve_default=False,
        ),
    ]
