# Generated by Django 6.0.4 on 2026-04-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_commande_reference_commande_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='pourboire',
            field=models.IntegerField(default=70),
        ),
        migrations.AddField(
            model_name='commande',
            name='total_avec_pourboire',
            field=models.IntegerField(default='70'),
            preserve_default=False,
        ),
    ]
